name: hello world workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dospatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chackout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash

  goodye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "goodbye world"
        shell: bash 
